name: Code Analysis Reusable

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    code_analysis_reusable:
        # see https://github.com/rectorphp/reusable-workflows
        uses: rectorphp/reusable-workflows/.github/workflows/code_analysis.yaml@main

    rector:
        # run only on main repository, not on the forks without access
        if: github.repository == 'rectorphp/rector-downgrade-php'

        # see https://github.com/rectorphp/reusable-workflows
        uses: rectorphp/reusable-workflows/.github/workflows/rector.yaml@main
